### ISSUE TITLE
OT48 - Cross button colour update

### ISSUE THREAD

**Issue by bappygolder** [bappygolder/oTask#48]
It seems the cross button's cross takes on a red colour for phones. We need to remove the native phone colour and apply the current white colour.

**Comment by anil826** [comment]
I am working on this issue..

**Comment by anil826** [comment]
Hi, this issue is fix now , the problem is related to unicode characters which is differently behave according to system , like in my Mac OS , on both bowser chrome & safari the Color is Red same like phone bowser. So i use font-awesome plugin to create a cross icon.

My changes are pushed on branch: master-OT48

**Comment by bappygolder** [comment]
It seems like you have only pushed to your own forked version of the code. You need to create a pull request so for our master branch so that I can see the changes. 

To do that you don't use the big green pull request button. You use the other pull request button that is located a little billow on the right hand side. If you can't find it just try using the browsers find option to find the other pull request button. 

If you have any other confusion feel free to call me on skype.

**Comment by bappygolder** [comment]
This is done thanks to Anil. The bootstrap inclusion seems to have broken some style but I'm in the process of fixing them.
